---
kind: pipeline
name: default

- name: build
  image: plugins/hugo
  commands:
  - git submodule update --init --recursive
  - git submodule update --remote --merge  
  settings:
    hugo_version: 0.92
    validate: false
    extended: true