---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Get theme and update to latest commit
  commands: 
  - git submodule update --init --recursive
  - git submodule update --remote --merge

- name: build
  image: plugins/hugo  
  settings:
    hugo_version: 0.92
    validate: false
    extended: true