baseURL: https://nawan.my.id
defaultContentLanguage: id
title: NAWAN
author: Nawan
theme: "PaperMod"
enableEmoji: true
enableRobotsTXT: true
enableInlineShortcodes: true

languages:
   id:
       languageName: "Bahasa Indonesia"
       weight: 1
       menu:
           main:
               - name: Arsip
                 url: archives
                 weight: 5
               - name: Wikipedia (user)
                 url: https://id.wikipedia.org/wiki/Pengguna:NawanP
                 weight: 5
               - name: Pencarian
                 url: search/
                 weight: 10
               - name: Label
                 url: tags/
                 weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    defaultheme: auto
    descrption: "Tempat peristirahatan terakhir bagi kata-kata"
    keywords: [blog, wikipedia, nawan]
    DateFormat: "2 Januari 2006"
    disableThemeToggle: false

    ShowShareButtons: true
    ShowReadingTime: true
    ShowPostNavLinks: true
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.ico"
        favicon32x32: "favicon-32x32.ico"
        apple_touch_icon: "apple-touch-icon.png"

    profileMode:
        enabled: true
        title: # optional default will be site title
        subtitle: "Hanya seorang mahasiswa kupu-kupu, menghabiskan waktu dengan rebahan dan menumpuk daftar tontonan Netflix. Sesekali mampir ke Wikipedia."
        imageUrl: "me.jpg" # optional
        imageTitle: "Ini adalah foto Nawan" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Postingan
              url: post
            - name: Kategori
              url: categories

    socialIcons:
        - name: twitter
          url: "https://twitter.com/nawanpangestu95"
        - name: instagram
          url: "https://www.instagram.com/nawanpangestu95/"
        - name: github
          url: "https://github.com/nawan95"
        - name: keybase
          url: "https://keybase.io/nawantpangestu"
        - name: discord
          url: "https://discordapp.com/users/768101555169656833"
        - name: steam
          url: "https://steamcommunity.com/id/sergiuv/"

taxonomies:
    category: categories
    tag: tags
