name: Deploy Hugo Site

on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.113.0'

      - name: Build Hugo Site
        run: hugo --minify

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2
        with:
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_path: "/home/nawanmyi/domains/nawan.my.id/public_html"
          local_path: "./public"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "--delete"
